# log configuration
logfile_path: '/var/log/reaper/reaper.log'
loglevel_console: 'logging.ERROR'
loglevel_file: 'logging.DEBUG'

# reaper_slave configuration
reaper_master: "reaper-master.example.com"
remote_user: "root"
packagemanager: "yum"
repository_data_path: "/var/repositories"
operatingsystem: "CentOS"
osmajorversion: 7
repositories:
  - "base"
  - "epel"