# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.define "master" do |master|
        master.vm.box = "centos/7"
        master.vm.hostname = "master"
        master.vm.provision :shell, path: "master-bootstrap.sh"
    end
    config.vm.define "client-centos6" do |centos6|
        centos6.vm.box = "centos/6"
        centos6.vm.hostname = "client-centos6"
        centos6.vm.provision :shell, path: "bootstrap.sh"
    end
    config.vm.define "client-centos7" do |centos7|
        centos7.vm.box = "centos/7"
        centos7.vm.hostname = "client-centos7"
        centos7.vm.provision :shell, path: "bootstrap.sh"
    end
end
