---
## clients ##
# List of used repo-clients to sync from
sources:
  '10.0.0.1':
     user: 'reaper'
     path: '/var/repo/'
  '10.1.0.1':
     user: 'reaper'
     path: '/var/repo2/'

# set folder where the packages on the master sould reside
master_repo: '/var/repo/latest'

# instances needed on the master-server
instances:
  - 'production'
  - 'testing'

# Webserver: apache or nginx
webserver: apache
