---
## clients ##
# List of used repo-clients to sync from
sources:
  '10.0.0.1':
     user: 'reaper'
     path: '/var/repo'
  '10.1.0.1':
     user: 'reaper'
     path: '/var/repo2'
## Server ##
# instances needed on the master-server
instances:
  - 'production'
  - 'testing'

# Webserver: apache or nginx
webserver: apache
