# Reaper_master configuration
# Logging Configuration
logfile_path: '/var/log/reaper'
loglevel_console: 'error'
loglevel_file: 'debug' 

# Master Configuration
document_root: "/var/www/html"
volumegroup: "repo-data"
logicalvolume: "repo01"
